{
  "formatVersion": "1.1",
  "component": {
    "group": "com.truefit",
    "module": "truefit-android-sdk",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "truefit-android-sdk-2.0.5.aar",
          "url": "truefit-android-sdk-2.0.5.aar",
          "size": 73090,
          "sha512": "5cc8f3594abb6b100c9c35a74640947b31ad0e52f97850933568131bae835872deaef241db3eb972566d3ec85cdb54df7717fe618e41ff827e2b07b44e0bcf1f",
          "sha256": "ec35714d7f33aa0ee7ac7d7654ddf936ecbd7388906573e56b31cca8085b816b",
          "sha1": "72cd3f47fb2e768e43aae6ffaee88193c2d8e9cf",
          "md5": "021d6538364d6f426f78eb3d8b02bd90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "truefit-android-sdk-2.0.5.aar",
          "url": "truefit-android-sdk-2.0.5.aar",
          "size": 73090,
          "sha512": "5cc8f3594abb6b100c9c35a74640947b31ad0e52f97850933568131bae835872deaef241db3eb972566d3ec85cdb54df7717fe618e41ff827e2b07b44e0bcf1f",
          "sha256": "ec35714d7f33aa0ee7ac7d7654ddf936ecbd7388906573e56b31cca8085b816b",
          "sha1": "72cd3f47fb2e768e43aae6ffaee88193c2d8e9cf",
          "md5": "021d6538364d6f426f78eb3d8b02bd90"
        }
      ]
    }
  ]
}
